# Generated by Django 6.0.1 on 2026-01-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='active',
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('graduated', 'Graduated'), ('failed', 'Failed'), ('studying', 'Studying')], default='Studying', max_length=10),
            preserve_default=False,
        ),
    ]
