# Generated by Django 6.0.1 on 2026-01-20 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_created_at_student_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('user__username',), 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
    ]
