# Generated by Django 6.0.1 on 2026-01-20 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ('courses',
     '0009_alter_category_name_alter_group_course_and_more'),
    ('students',
     '0003_remove_student_status_enrollment'),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

  operations = [
    migrations.AlterModelOptions(
      name='enrollment',
      options={
        'ordering': [ '-created_at' ],
        'verbose_name': 'Enrollment',
        'verbose_name_plural': 'Enrollments',
        },
      ),
    migrations.AddField(
      model_name='enrollment',
      name='grade',
      field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
      ),
    migrations.AddField(
      model_name='enrollment',
      name='last_attended',
      field=models.DateField(blank=True, null=True),
      ),
    migrations.AlterField(
      model_name='enrollment',
      name='status',
      field=models.CharField(choices=[ ('graduated',
                                        'Graduated'), ('failed',
                                                       'Failed'), ('studying',
                                                                   'Studying'), ('dropped',
                                                                                 'Dropped') ], default='studying',
                             max_length=15,
                             ),
      ),
    migrations.AlterField(
      model_name='enrollment',
      name='student',
      field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments',
                              to='students.student',
                              ),
      ),
    migrations.AlterField(
      model_name='student',
      name='address',
      field=models.CharField(blank=True, max_length=250, null=True),
      ),
    migrations.AlterField(
      model_name='student',
      name='phone',
      field=models.CharField(blank=True, max_length=20, null=True),
      ),
    migrations.AlterField(
      model_name='student',
      name='user',
      field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile',
                                 to=settings.AUTH_USER_MODEL,
                                 ),
      ),
    migrations.AlterUniqueTogether(
      name='enrollment',
      unique_together={ ('student',
                         'course') },
      ),
    ]
