# Generated by Django 6.0.1 on 2026-01-20 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ('courses',
     '0010_session_group_session'),
    ('students',
     '0004_alter_enrollment_options_enrollment_grade_and_more'),
    ]

  operations = [
    migrations.AddField(
      model_name='enrollment',
      name='session',
      field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                              related_name='enrollments', to='courses.session',
                              ),
      ),
    ]
