# Generated by Django 6.0.1 on 2026-01-20 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ('attendance',
     '0003_alter_attendance_marked_by_alter_attendance_student_and_more'),
    ('finance',
     '0003_alter_payment_student'),
    ('students',
     '0005_enrollment_session'),
    ('tasks',
     '0002_alter_submission_options_and_more'),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

  operations = [
    migrations.AlterField(
      model_name='enrollment',
      name='student',
      field=models.ForeignKey(limit_choices_to={
        'role': 'student',
        }, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL,
        ),
      ),
    migrations.DeleteModel(
      name='Student',
      ),
    ]
