# Generated by Django 6.0.1 on 2026-01-21 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_comment_course_alter_comment_user'),
        ('students', '0006_alter_enrollment_student_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='courses.group'),
        ),
    ]
