# Generated by Django 6.0.1 on 2026-01-20 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ('finance',
     '0001_initial'),
    ('students',
     '0004_alter_enrollment_options_enrollment_grade_and_more'),
    ]

  operations = [
    migrations.AddField(
      model_name='payment',
      name='enrollment',
      field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                              related_name='payments', to='students.enrollment',
                              ),
      ),
    migrations.AlterField(
      model_name='payment',
      name='student',
      field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments',
                              to='students.student',
                              ),
      ),
    ]
