# Generated by Django 6.0.1 on 2026-01-20 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ('finance',
     '0002_payment_enrollment_alter_payment_student'),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

  operations = [
    migrations.AlterField(
      model_name='payment',
      name='student',
      field=models.ForeignKey(limit_choices_to={
        'role': 'student',
        }, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL,
        ),
      ),
    ]
