# Generated by Django 6.0.1 on 2026-01-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_payment_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('balance', 'Student Balance')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('tuition', 'Tuition Fee'), ('registration', 'Registration Fee'), ('exam', 'Exam Fee'), ('deposit', 'Deposit'), ('monthly', 'Monthly Charge'), ('other', 'Other')], default='tuition', max_length=20),
        ),
    ]
