# Generated by Django 6.0.1 on 2026-01-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ('accounts',
     '0001_initial'),
    ]

  operations = [
    migrations.AddField(
      model_name='user',
      name='address',
      field=models.CharField(blank=True, max_length=250, null=True),
      ),
    migrations.AddField(
      model_name='user',
      name='is_expert',
      field=models.BooleanField(default=False),
      ),
    migrations.AddField(
      model_name='user',
      name='phone',
      field=models.CharField(blank=True, max_length=20, null=True),
      ),
    migrations.AddField(
      model_name='user',
      name='qualifications',
      field=models.TextField(blank=True, null=True),
      ),
    migrations.AddField(
      model_name='user',
      name='speciality',
      field=models.CharField(blank=True, max_length=100, null=True),
      ),
    ]
