# Generated by Django 6.0.1 on 2026-01-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_expert',
            field=models.BooleanField(default=False),
        ),
    ]
