# Generated by Django 6.0.1 on 2026-01-20 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_created_at_teacher_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ('user__username',), 'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
    ]
