# Generated by Django 6.0.1 on 2026-01-20 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ('teachers',
     '0002_teacher_is_expert'),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

  operations = [
    migrations.AddField(
      model_name='teacher',
      name='phone',
      field=models.CharField(blank=True, max_length=20, null=True),
      ),
    migrations.AddField(
      model_name='teacher',
      name='qualifications',
      field=models.TextField(blank=True, null=True),
      ),
    migrations.AlterField(
      model_name='teacher',
      name='user',
      field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile',
                                 to=settings.AUTH_USER_MODEL,
                                 ),
      ),
    ]
