# Generated by Django 6.0.1 on 2026-01-20 23:24

from django.db import migrations


class Migration(migrations.Migration):
  dependencies = [
    ('attendance',
     '0003_alter_attendance_marked_by_alter_attendance_student_and_more'),
    ('courses',
     '0011_alter_group_teacher'),
    ('tasks',
     '0002_alter_submission_options_and_more'),
    ('teachers',
     '0003_teacher_phone_teacher_qualifications_and_more'),
    ]

  operations = [
    migrations.DeleteModel(
      name='Teacher',
      ),
    ]
