# Generated by Django 6.0.1 on 2026-01-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='large_description',
            field=models.TextField(default='large desc', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='large_image',
            field=models.ImageField(null=True, upload_to='courses/large_images'),
        ),
        migrations.AddField(
            model_name='course',
            name='small_description',
            field=models.TextField(default='small desc', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='small_image',
            field=models.ImageField(null=True, upload_to='courses/small_images'),
        ),
    ]
