# Generated by Django 6.0.1 on 2026-01-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_large_description_course_large_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
    ]
