# Generated by Django 6.0.1 on 2026-01-20 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_comment_updated_at_course_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_at',), 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('name',), 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('name',), 'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
    ]
