# Generated by Django 6.0.1 on 2026-01-20 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ('courses',
     '0004_alter_course_price'),
    ]

  operations = [
    migrations.CreateModel(
      name='Category',
      fields=[
        ('id',
         models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('name',
         models.CharField(max_length=50)),
        ('created_at',
         models.DateTimeField(auto_now_add=True)),
        ('updated_at',
         models.DateTimeField(auto_now=True)),
        ],
      ),
    migrations.AddField(
      model_name='course',
      name='category',
      field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.category'),
      preserve_default=False,
      ),
    ]
