# Generated by Django 6.0.1 on 2026-01-20 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ('courses',
     '0005_category_course_category'),
    ]

  operations = [
    migrations.AlterField(
      model_name='course',
      name='category',
      field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                              related_name='courses', to='courses.category',
                              ),
      ),
    ]
