# Generated by Django 6.0.1 on 2026-01-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ('courses',
     '0006_alter_course_category'),
    ]

  operations = [
    migrations.AlterField(
      model_name='category',
      name='name',
      field=models.CharField(blank=True, max_length=50, null=True, unique=True),
      ),
    ]
