# Generated by Django 6.0.1 on 2026-01-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ('courses',
     '0007_alter_category_name'),
    ]

  operations = [
    migrations.AlterField(
      model_name='category',
      name='name',
      field=models.CharField(blank=True, default='1', max_length=50, null=True, unique=True),
      ),
    ]
