# Generated by Django 6.0.1 on 2026-01-20 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ('courses',
     '0008_alter_category_name'),
    ('teachers',
     '0003_teacher_phone_teacher_qualifications_and_more'),
    ]

  operations = [
    migrations.AlterField(
      model_name='category',
      name='name',
      field=models.CharField(blank=True, max_length=50, null=True, unique=True),
      ),
    migrations.AlterField(
      model_name='group',
      name='course',
      field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='courses.course'),
      ),
    migrations.AlterField(
      model_name='group',
      name='teacher',
      field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_groups',
                              to='teachers.teacher',
                              ),
      ),
    migrations.AlterUniqueTogether(
      name='group',
      unique_together={ ('course',
                         'name') },
      ),
    ]
