# Generated by Django 6.0.1 on 2026-01-20 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ('courses',
     '0009_alter_category_name_alter_group_course_and_more'),
    ]

  operations = [
    migrations.CreateModel(
      name='Session',
      fields=[
        ('id',
         models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('session_type',
         models.CharField(choices=[ ('1st',
                                     '1st Session'), ('2nd',
                                                      '2nd Session'), ('3rd',
                                                                       '3rd Session'), ('4th',
                                                                                        '4th Session'), ('spring',
                                                                                                         'Spring'),
                                    ('summer',
                                     'Summer'), ('fall',
                                                 'Fall'), ('winter',
                                                           'Winter') ], max_length=20,
                          )),
        ('start_date',
         models.DateField()),
        ('end_date',
         models.DateField()),
        ('capacity',
         models.PositiveIntegerField(default=30)),
        ('is_active',
         models.BooleanField(default=True)),
        ('created_at',
         models.DateTimeField(auto_now_add=True)),
        ('updated_at',
         models.DateTimeField(auto_now=True)),
        ('course',
         models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='courses.course')),
        ],
      options={
        'verbose_name': 'Session',
        'verbose_name_plural': 'Sessions',
        'ordering': ('course',
                     'session_type'),
        'unique_together': { ('course',
                              'session_type') },
        },
      ),
    migrations.AddField(
      model_name='group',
      name='session',
      field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups',
                              to='courses.session',
                              ),
      ),
    ]
