# Generated by Django 6.0.1 on 2026-01-20 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ('courses',
     '0010_session_group_session'),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

  operations = [
    migrations.AlterField(
      model_name='group',
      name='teacher',
      field=models.ForeignKey(blank=True, limit_choices_to={
        'role': 'teacher',
        }, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_groups',
                              to=settings.AUTH_USER_MODEL,
                              ),
      ),
    ]
