# Generated by Django 6.0.1 on 2026-01-20 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ('courses',
     '0011_alter_group_teacher'),
    ('tasks',
     '0001_initial'),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

  operations = [
    migrations.AlterModelOptions(
      name='submission',
      options={
        'ordering': ('-created_at',),
        'verbose_name': 'Submission',
        'verbose_name_plural': 'Submissions',
        },
      ),
    migrations.AlterUniqueTogether(
      name='submission',
      unique_together={ ('assignment',
                         'student') },
      ),
    migrations.AddField(
      model_name='assignment',
      name='group',
      field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                              related_name='assignments', to='courses.group',
                              ),
      ),
    migrations.AddField(
      model_name='assignment',
      name='status',
      field=models.CharField(choices=[ ('draft',
                                        'Draft'), ('published',
                                                   'Published'), ('closed',
                                                                  'Closed') ], default='draft', max_length=15,
                             ),
      ),
    migrations.AddField(
      model_name='submission',
      name='status',
      field=models.CharField(choices=[ ('submitted',
                                        'Submitted'), ('graded',
                                                       'Graded'), ('late',
                                                                   'Late') ], default='submitted', max_length=15,
                             ),
      ),
    migrations.AlterField(
      model_name='assignment',
      name='created_at',
      field=models.DateTimeField(auto_now_add=True),
      ),
    migrations.AlterField(
      model_name='assignment',
      name='description',
      field=models.TextField(),
      ),
    migrations.AlterField(
      model_name='assignment',
      name='teacher',
      field=models.ForeignKey(limit_choices_to={
        'role': 'teacher',
        }, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL,
        ),
      ),
    migrations.AlterField(
      model_name='submission',
      name='assignment',
      field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions',
                              to='tasks.assignment',
                              ),
      ),
    migrations.AlterField(
      model_name='submission',
      name='file',
      field=models.FileField(upload_to='submissions/%Y/%m/%d/'),
      ),
    migrations.AlterField(
      model_name='submission',
      name='student',
      field=models.ForeignKey(limit_choices_to={
        'role': 'student',
        }, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL,
        ),
      ),
    migrations.RemoveField(
      model_name='submission',
      name='checked',
      ),
    ]
