# Generated by Django 6.0.1 on 2026-01-21 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_marked_by_alter_attendance_student_and_more'),
        ('tasks', '0002_alter_submission_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='attendance.schedule'),
        ),
    ]
