# Generated by Django 6.0.1 on 2026-01-20 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ('attendance',
     '0001_initial'),
    ('courses',
     '0009_alter_category_name_alter_group_course_and_more'),
    ('students',
     '0004_alter_enrollment_options_enrollment_grade_and_more'),
    ('teachers',
     '0003_teacher_phone_teacher_qualifications_and_more'),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

  operations = [
    migrations.AddField(
      model_name='attendance',
      name='notes',
      field=models.TextField(blank=True, null=True),
      ),
    migrations.AlterField(
      model_name='attendance',
      name='marked_by',
      field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                              to=settings.AUTH_USER_MODEL,
                              ),
      ),
    migrations.AlterField(
      model_name='attendance',
      name='status',
      field=models.CharField(choices=[ ('present',
                                        'Present'), ('absent',
                                                     'Absent'), ('late',
                                                                 'Late'), ('excused',
                                                                           'Excused') ], max_length=10,
                             ),
      ),
    migrations.AlterField(
      model_name='attendance',
      name='student',
      field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records',
                              to='students.student',
                              ),
      ),
    migrations.CreateModel(
      name='Schedule',
      fields=[
        ('id',
         models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('day_of_week',
         models.IntegerField(choices=[ (0,
                                        'Monday'), (1,
                                                    'Tuesday'), (2,
                                                                 'Wednesday'), (3,
                                                                                'Thursday'), (4,
                                                                                              'Friday'), (5,
                                                                                                          'Saturday'),
                                       (6,
                                        'Sunday') ],
                             )),
        ('start_time',
         models.TimeField()),
        ('end_time',
         models.TimeField()),
        ('room',
         models.CharField(blank=True, max_length=50, null=True)),
        ('created_at',
         models.DateTimeField(auto_now_add=True)),
        ('updated_at',
         models.DateTimeField(auto_now=True)),
        ('group',
         models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots',
                           to='courses.group',
                           )),
        ('teacher',
         models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                           related_name='schedule_slots', to='teachers.teacher',
                           )),
        ],
      options={
        'verbose_name': 'Schedule',
        'verbose_name_plural': 'Schedules',
        'ordering': ('day_of_week',
                     'start_time'),
        },
      ),
    migrations.AlterUniqueTogether(
      name='attendance',
      unique_together=set(),
      ),
    migrations.AddField(
      model_name='attendance',
      name='schedule',
      field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                              related_name='attendance_records', to='attendance.schedule',
                              ),
      ),
    migrations.AlterUniqueTogether(
      name='attendance',
      unique_together={ ('student',
                         'schedule',
                         'date') },
      ),
    migrations.AddIndex(
      model_name='attendance',
      index=models.Index(fields=[ 'student', 'date' ], name='attendance__student_76a8d7_idx'),
      ),
    migrations.AddIndex(
      model_name='attendance',
      index=models.Index(fields=[ 'schedule', 'date' ], name='attendance__schedul_294061_idx'),
      ),
    migrations.AlterUniqueTogether(
      name='schedule',
      unique_together={ ('group',
                         'day_of_week',
                         'start_time') },
      ),
    ]
