# Generated by Django 6.0.1 on 2026-01-20 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ('attendance',
     '0002_attendance_notes_alter_attendance_marked_by_and_more'),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

  operations = [
    migrations.AlterField(
      model_name='attendance',
      name='marked_by',
      field=models.ForeignKey(blank=True, limit_choices_to={
        'role': 'teacher',
        }, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances',
                              to=settings.AUTH_USER_MODEL,
                              ),
      ),
    migrations.AlterField(
      model_name='attendance',
      name='student',
      field=models.ForeignKey(limit_choices_to={
        'role': 'student',
        }, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL,
        ),
      ),
    migrations.AlterField(
      model_name='schedule',
      name='teacher',
      field=models.ForeignKey(blank=True, limit_choices_to={
        'role': 'teacher',
        }, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_slots',
                              to=settings.AUTH_USER_MODEL,
                              ),
      ),
    ]
